export const majorCodes: Record<string, string> = {
  'ACCOFIN-BS': 'Accounting and Finance (BS)',
  'ACCOUN-BS': 'Accounting (BS)',
  'ACTSTS-BFA': 'Acting, Stage and Screen (BFA)',
  'AEAA-BA': 'American Studies and Ethnicity (African American Studies) (BA)',
  'AEAA-BA1': 'American Studies and Ethnicity (Asian American Studies) (BA)',
  'AECL-BA': 'American Studies and Ethnicity (Chicano/Latino Studies) (BA)',
  'AEROENG-BS': 'Aerospace Engineering (BS)',
  'AMEPOCU-BA': 'American Popular Culture (BA)',
  'AMERETH-BA': 'American Studies and Ethnicity (BA)',
  'ANIDIA-BFA': 'Animation and Digital Arts (BFA)',
  'ANTHRO-BA': 'Anthropology (BA)',
  'ANTVIAN-BA': 'Anthropology (Visual Anthropology) (BA)',
  'APPCOMA-BA': 'Applied and Computational Mathematics (BA)',
  'APPCOMA-BS': 'Applied and Computational Mathematics (BS)',
  'ARCHBAR': 'Architecture (BArch)',
  'ARCHHER-BA': 'Archaeology and Heritage Studies (BA)',
  'ARCHIT-BS': 'Architectural Studies (BS)',
  'ARCINTE-BS': 'Architecture and Inventive Technologies (BS)',
  'ART-BA': 'Art (BA)',
  'ARTHIS-BA': 'Art History (BA)',
  'ARTIINT-BS': 'Artificial Intelligence (BS)',
  'ARTINBU-BS': 'Artificial Intelligence for Business (BS)',
  'ASTRENG-BS': 'Astronautical Engineering (BS)',
  'ASTRON-BA': 'Astronomy (BA)',
  'ASTRON-BS': 'Astronomy (BS)',
  'ATBI-BS': 'Arts, Technology and the Business of Innovation (BS)',
  'BABA-BS': 'Business Administration (Business Analytics) (BS)',
  'BACA-BS': 'Business Administration (Cinematic Arts) (BS)',
  'BAEI-BS': 'Business Administration (Entrepreneurship and Innovation) (BS)',
  'BAIR-BS': 'Business Administration (International Relations) (BS)',
  'BALI-BS': 'Business Administration (Leadership and Innovation) (BS)',
  'BAREF-BS': 'Business Administration (Real Estate Finance) (BS)',
  'BARM-BS': 'Business Administration (Risk Management) (BS)',
  'BAWP-BS': 'Business Administration (World Program) (BS)',
  'BEEE-BS': 'Biomedical Engineering, Electrical Engineering Emphasis (BS)',
  'BEHECPS-BA': 'Behavioral Economics and Psychology (BA)',
  'BEMCE-BS': 'Biomedical Engineering, Molecular and Cellular Engineering Emphasis (BS)',
  'BEME-BS': 'Biomedical Engineering, Mechanical Engineering Emphasis (BS)',
  'BIOCHE-BS': 'Biochemistry (BS)',
  'BIOLSCI-BA': 'Biological Sciences (BA)',
  'BIOLSCI-BS': 'Biological Sciences (BS)',
  'BIOMENG-BS': 'Biomedical Engineering (BS)',
  'BIOPHY-BS': 'Biophysics (BS)',
  'BIOPSCI-BA': 'Biopharmaceutical Sciences (BA)',
  'BIOPSCI-BS': 'Biopharmaceutical Sciences (BS)',
  'BIOSCBI-BS': 'Biological Sciences (Biotechnology) (BS)',
  'BSEEE-BS': 'Biological Sciences (Ecology, Evolution and Environment) (BS)',
  'BSMB-BS': 'Biological Sciences (Marine Biology) (BS)',
  'BSMCDB-BS': 'Biological Sciences (Molecular, Cellular and Developmental Biology) (BS)',
  'BUSADCO-BS': 'Business Administration (Communication) (BS)',
  'BUSADFI-BS': 'Business Administration (Finance) (BS)',
  'BUSADMA-BS': 'Business Administration (Marketing) (BS)',
  'BUSCIAR-BS': 'Business of Cinematic Arts (BS)',
  'BUSIADM-BS': 'Business Administration (BS)',
  'BUSIINN-BS': 'Business of Innovation (BS)',
  'CAFTP-BA': 'Cinematic Arts, Film and Television Production (BA)',
  'CAFTP-BFA': 'Cinematic Arts, Film and Television Production (BFA)',
  'CEBPE-BS': 'Chemical Engineering, Biological and Pharmaceutical Engineering Emphasis (BS)',
  'CEBS-BS': 'Civil Engineering, Building Science Emphasis (BS)',
  'CECEM-BS': 'Civil Engineering, Construction Engineering and Management Emphasis (BS)',
  'CECS-BS': 'Computer Engineering and Computer Science (BS)',
  'CEEE-BS': 'Civil Engineering, Environmental Engineering Emphasis (BS)',
  'CEES-BS': 'Chemical Engineering, Energy and Sustainability Emphasis (BS)',
  'CEME-BS': 'Chemical Engineering, Materials Engineering Emphasis (BS)',
  'CENTEUR-BA': 'Central European Studies (BA)',
  'CEPSE-BS': 'Chemical Engineering, Petroleum and Subsurface Engineering Emphasis (BS)',
  'CESE-BS': 'Civil Engineering, Structural Engineering Emphasis (BS)',
  'CEWRE-BS': 'Civil Engineering, Water Resources Engineering Emphasis (BS)',
  'CHECHBI-BS': 'Chemistry (Chemical Biology) (BS)',
  'CHECHNA-BS': 'Chemistry (Chemical Nanoscience) (BS)',
  'CHEMENG-BS': 'Chemical Engineering (BS)',
  'CHEMIS-BA': 'Chemistry (BA)',
  'CHEMIS-BS': 'Chemistry (BS)',
  'CHEMRES-BS': 'Chemistry (Research) (BS)',
  'CHORMUS-BA': 'Choral Music (BA)',
  'CHORMUS-BM': 'Choral Music (BM)',
  'CINEMED-BA': 'Cinema and Media Studies (BA)',
  'CIVIENG-BS': 'Civil Engineering (BS)',
  'CLASSI-BA': 'Classics (BA)',
  'CLLA-BA': 'Contemporary Latino and Latin American Studies (BA)',
  'COGNSCI-BA': 'Cognitive Science (BA)',
  'COMMUN-BA': 'Communication (BA)',
  'COMPLIN-BS': 'Computational Linguistics (BS)',
  'COMPLIT-BA': 'Comparative Literature (BA)',
  'COMPNEU-BS': 'Computational Neuroscience (BS)',
  'COMPOS-BM': 'Composition (BM)',
  'COMPSCI-BS': 'Computer Science (BS)',
  'COMSCGA-BS': 'Computer Science Games (BS)',
  'CSBA-BS': 'Computer Science/Business Administration (BS)',
  'DAMT-BA': 'Dramatic Arts, Musical Theatre Emphasis (BA)',
  'DANCE-BFA': 'Dance (BFA)',
  'DATASCI-BA': 'Data Science (BA)',
  'DESIGN-BFA': 'Design (BFA)',
  'DRAARAC-BA': 'Dramatic Arts, Acting Emphasis (BA)',
  'DRAARCO-BA': 'Dramatic Arts, Comedy Emphasis (BA)',
  'DRAARDE-BA': 'Dramatic Arts, Design Emphasis (BA)',
  'DRAARDI-BA': 'Dramatic Arts, Directing Emphasis (BA)',
  'DRAMART-BA': 'Dramatic Arts (BA)',
  'EALC-BA': 'East Asian Languages and Cultures (BA)',
  'EARTSCI-BA': 'Earth Sciences (BA)',
  'EASTASI-BA': 'East Asian Area Studies (BA)',
  'ECODASC-BS': 'Economics and Data Science (BS)',
  'ECONMAT-BS': 'Economics/Mathematics (BS)',
  'ECONOM-BA': 'Economics (BA)',
  'ELECOEN-BS': 'Electrical and Computer Engineering (BS)',
  'ENGLIS-BA': 'English (BA)',
  'ENVIENG-BS': 'Environmental Engineering (BS)',
  'ENVIRO-BA': 'Environmental Studies (BA)',
  'ENVIRO-BS': 'Environmental Studies (BS)',
  'ENVSCHE-BA': 'Environmental Science and Health (BA)',
  'ENVSCHE-BS': 'Environmental Science and Health (BS)',
  'FINEAR-BFA': 'Fine Arts (BFA)',
  'FRENCH-BA': 'French (BA)',
  'GAMEAR-BFA': 'Game Art (BFA)',
  'GDID-BFA': 'Game Development and Interactive Design (BFA)',
  'GENDSEX-BA': 'Gender and Sexuality Studies (BA)',
  'GEODES-BS': 'Geodesign (BS)',
  'GEOLSCI-BS': 'Geological Sciences (BS)',
  'GLOBAL-BA': 'Global Studies (BA)',
  'GLOBGEO-BS': 'Global Geodesign (BS)',
  'GLOBHEA-BS': 'Global Health Studies (BS)',
  'HDAH-BS': 'Human Development and Aging, Honors Programs (BS)',
  'HDAHS-BS': 'Human Development and Aging, Health Science Track (BS)',
  'HEAHUSC-BA': 'Health and Human Sciences (BA)',
  'HEALHUM-BA': 'Health and Humanity (BA)',
  'HISTOR-BA': 'History (BA)',
  'HPDP-BS': 'Health Promotion and Disease Prevention Studies (BS)',
  'HSGI-BS': 'Human Security and Geospatial Intelligence (BS)',
  'HUMABIO-BA': 'Human Biology (BA)',
  'HUMABIO-BS': 'Human Biology (BS)',
  'HUMDEAG-BS': 'Human Development and Aging (BS)',
  'HUMTEIN-BS': 'Human Technology Interaction (BS)',
  'INDSYEN-BS': 'Industrial and Systems Engineering (BS)',
  'INTCYOP-BA': 'Intelligence and Cyber Operations (BA)',
  'INTERD-BA': 'Interdisciplinary Studies (BA)',
  'INTEREL-BA': 'International Relations (BA)',
  'IRGB-BA': 'International Relations (Global Business) (BA)',
  'IRGE-BA': 'International Relations and the Global Economy (BA)',
  'ITALIA-BA': 'Italian (BA)',
  'JAZZ-BM': 'Jazz Studies (BM)',
  'JEWISH-BA': 'Jewish Studies (BA)',
  'JOURNA-BA': 'Journalism (BA)',
  'LAICMP-BA': 'Latin American and Iberian Cultures, Media and Politics (BA)',
  'LAWHICU-BA': 'Law, History, and Culture (BA)',
  'LEALC-BA': 'Linguistics and East Asian Languages and Cultures (BA)',
  'LEGAL-BS': 'Legal Studies (BS)',
  'LIFEHEA-BS': 'Lifespan Health (BS)',
  'LINCOSC-BA': 'Linguistics and Cognitive Science (BA)',
  'LINGPHI-BA': 'Linguistics and Philosophy (BA)',
  'LINGUI-BA': 'Linguistics (BA)',
  'MATHECO-BS': 'Mathematics/Economics (BS)',
  'MATHEM-BA': 'Mathematics (BA)',
  'MATHEM-BS': 'Mathematics (BS)',
  'MECHENG-BS': 'Mechanical Engineering (BS)',
  'MEDARPR-BA': 'Media Arts and Practice (BA)',
  'MIDDEAS-BA': 'Middle East Studies (BA)',
  'MUSIC-BA': 'Music (BA)',
  'MUSIIND-BM': 'Music Industry (BM)',
  'MUSIIND-BS': 'Music Industry (BS)',
  'MUSIPRO-BM': 'Music Production (BM)',
  'MUSITH-BFA': 'Musical Theatre (BFA)',
  'NARRAT-BA': 'Narrative Studies (BA)',
  'NEUROS-BA': 'Neuroscience (BA)',
  'NEUROS-BS': 'Neuroscience (BS)',
  'NGOSC-BA': 'Non-Governmental Organizations and Social Change (BA)',
  'OCCUTHE-BS': 'Occupational Therapy (BS)',
  'PERCLGU-BM': 'Performance (Classical Guitar) (BM)',
  'PERFORG-BM': 'Performance (Organ) (BM)',
  'PERFPIA-BM': 'Performance (Piano) (BM)',
  'PERPOMU-BM': 'Performance (Popular Music) (BM)',
  'PERSTGU-BM': 'Performance (Studio Guitar) (BM)',
  'PERVOAR-BM': 'Performance (Vocal Arts) (BM)',
  'PFOCBSF-BM': 'Performance (Flute), (Oboe), (Clarinet), (Bassoon), (Saxophone), (French Horn), (Trumpet), (Trombone), (Tuba) or (Percussion) (BM)',
  'PHADRDE-BA': 'Pharmacology and Drug Development (BA)',
  'PHADRDE-BS': 'Pharmacology and Drug Development (BS)',
  'PHILOS-BA': 'Philosophy (BA)',
  'PHIPOEC-BA': 'Philosophy, Politics and Economics (BA)',
  'PHIPOLA-BA': 'Philosophy, Politics and Law (BA)',
  'PHYCOSC-BS': 'Physics/Computer Science (BS)',
  'PHYSIC-BA': 'Physics (BA)',
  'PHYSIC-BS': 'Physics (BS)',
  'PHYSSCI-BS': 'Physical Sciences (BS)',
  'POLIECO-BA': 'Political Economy (BA)',
  'POLISCI-BA': 'Political Science (BA)',
  'PSYCHO-BA': 'Psychology (BA)',
  'PUBLPOL-BS': 'Public Policy (BS)',
  'PUBREAD-BA': 'Public Relations and Advertising (BA)',
  'PVVVDBH-BM': 'Performance (Violin), (Viola), (Violoncello), (Double Bass) or (Harp) (BM)',
  'QUANBIO-BS': 'Quantitative Biology (BS)',
  'REAESDE-BS': 'Real Estate Development (BS)',
  'REFD-BS': 'Real Estate Finance and Development (BS)',
  'RELIGI-BA': 'Religion (BA)',
  'RUSSIA-BA': 'Russian (BA)',
  'SOCIOL-BA': 'Sociology (BA)',
  'SOCIWO-BSW': 'Social Work (BSW)',
  'SOCSCEC-BA': 'Social Sciences, with an Emphasis in Economics (BA)',
  'SOCSCPS-BA': 'Social Sciences, with an Emphasis in Psychology (BA)',
  'SOUNDE-BFA': 'Sound Design (BFA)',
  'SPANIS-BA': 'Spanish (BA)',
  'STAGMA-BFA': 'Stage Management (BFA)',
  'TECHDI-BFA': 'Technical Direction (BFA)',
  'THEADE-BFA': 'Theatrical Design (BFA)',
  'THEMEN-BFA': 'Themed Entertainment (BFA)',
  'URBAPLA-BS': 'Urban Studies and Planning (BS)',
  'VISPEAR-BA': 'Visual and Performing Arts Studies (BA)',
  'WRISCT-BFA': 'Writing for Screen and Television (BFA)',
};
